language: go
go_import_path: github.com/whiteblock/genesis
sudo: false
env:
   - GOPATH=/home/travis/gopath
#  - GO111MODULE=on

os: linux
dist: xenial
sudo: required
go: 1.12.x

before_install:
  - make install-mock
  - make mocks
  - go get -u golang.org/x/lint/golint

install:
  - ./.travis.gofmt.sh

script:
  - golint -set_exit_status $(go list ./... | grep -v mocks)
  - make vet
  - make test
  - go get ./...
  - go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success: bash <(curl -s https://codecov.io/bash)
