language: go
go_import_path: github.com/whiteblock/genesis
sudo: false
env:
#  - GO111MODULE=on
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      install:
        - sudo apt-get install golint -y
      after_success:
        - bash <(curl -s https://codecov.io/bash)
