language: go
go_import_path: github.com/whiteblock/genesis
sudo: true
env:
   - GOPATH=/home/travis/gopath
#  - GO111MODULE=on

os: linux
dist: xenial
sudo: required
go: 1.12.x

before_install:
  - go get github.com/vektra/mockery/.../
  - make mocks
  - sudo apt update
  - sudo apt install -y golint

script:
  - sh .travis.gofmt.sh
  - golint -set_exit_status $(go list ./... | grep -v mocks)
  - make vet
  - make test
  - go get ./...
  - go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success: bash <(curl -s https://codecov.io/bash)
