# You can put me in /etc/whiteblock/ or ~/.config/whiteblock/
# I should be called genesis.yaml
# SSH options
handleNodeSshKeys: true
nodesPublicKey: "/home/master-secrets/id.master.pub"
nodesPrivateKey: "/home/master-secrets/id.master"

# Server
listen: "127.0.0.1:8000"

# Log
verbosity: "INFO"
logJson: false

# Network
serverBits: 8
clusterBits: 12
nodeBits: 4
ipPrefix: 10
serviceNetwork: "172.30.0.1/16"

# Node
nodePrefix: "whiteblock-node"
nodeNetworkPrefix: "wb_vlan_"
maxNodeMemory: "16gb"
maxNodeCpu: 16

# Service
serviceNetworkName: "wb_builtin_services"
servicePrefix: "wb_service"
influx: "127.0.0.1:8086"
influxUser: ""
influxPassword: ""

# Misc
maxRunAttempts: 30
maxConnections: 50
nibblerEndPoint: "https://storage.googleapis.com/genesis-public/nibbler/dev/bin/linux/amd64/nibbler"
disableNibbler: false
disableTestnetReporting: false
maxCommandOutputLogSize: 200000 #200kB max output to be logged